modLoader="javafml"
loaderVersion="[48,)"
license="MIT License"
[[mods]]
modId="hostilewatermobs"
version="${file.jarVersion}"
displayName="Hostile Water Mobs"
displayURL="https://www.curseforge.com/minecraft/mc-mods/hostile-water-monsters"
updateJSONURL="https://github.com/mactso/harderfishesandamphibians/raw/master/update.json"
logoFile="Logo.png"
authors="MacTso, Lupicus"
description='Hostile Water Mobs.'
[[dependencies.hostilewatermobs]]
    modId="forge"
    mandatory=true
    versionRange="[48,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.hostilewatermobs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.2,1.21)"
    ordering="NONE"
    side="BOTH"
