modLoader="javafml"
loaderVersion="[32,)"
license="MIT License"
[[mods]]
modId="hostilewatermobs"
version="${file.jarVersion}"
displayName="Hostile Water Mobs"
displayURL="https://www.curseforge.com/minecraft/mc-mods/harderfishesandamphibians"
updateJSONURL="https://github.com/mactso/harderfishesandamphibians/raw/master/update.json"
logoFile="Logo.png"
authors="MacTso, Lupicus"
description='Hostile Water Mobs.'
[[dependencies.hostilewatermobs]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="SERVER"

[[dependencies.hostilewatermobs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="SERVER"
